version: 2.1

orbs:
   heroku: circleci/heroku@1.2.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "Hello World" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output

  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
